#!/bin/sh /etc/rc.common

START=54
USE_PROCD=1
DEPEND=fstab,mcu_update

start_service() {
	[ -e /tmp/.stress_test ] && exit 0

	procd_open_instance
	procd_set_param env HOME=/root
	procd_set_param command klipper_mcu -r
	procd_close_instance
}

